[package]
name = "zed_gdscript"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

# [lints]
# workspace = true

[lib]
path = "src/gdscript.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
