id = "gdscript"
name = "GDScript"
version = "0.0.3"
schema_version = 1
authors = ["Mark Brand <mark@grndctrl.com>"]
description = "GDScript language support for Zed"
repository = "https://github.com/grndctrl/zed-gdscript"

[grammars.gdscript]
repository = "https://github.com/PrestonKnopp/tree-sitter-gdscript"
commit = "b5dea4d852db65f0872d849c24533eb121e03c76"
