id = "gdscript"
name = "GDScript"
version = "0.1.0"
schema_version = 1
authors = ["Mark Brand <mark@grndctrl.com>"]
description = "GDScript language support for Zed"
repository = "https://github.com/grndctrl/zed-gdscript"

[language_servers.gdscript]
name = "GDScript Language Server"
language = "GDScript"

[grammars.gdscript]
repository = "https://github.com/PrestonKnopp/tree-sitter-gdscript"
commit = "b5dea4d852db65f0872d849c24533eb121e03c76"

[grammars.godot_resource]
repository = "https://github.com/PrestonKnopp/tree-sitter-godot-resource"
commit = "b6ef0768711086a86b3297056f9ffb5cc1d77b4a"
